// Local app data — no json-server needed.
// (Migrated from db/db.json so the UI works with only `npm run dev`.)

export const profile = {
  id: 1,
  username: "Edward",
  profilePic: "/assets/150.jpg",
};

export const posts = [
  {
    id: 1,
    username: "Edward",
    profilePic: "/assets/150.jpg",
    location: "Chennai, India",
    image: "/assets/p1.jpg",
    caption: "Lost in nature 🌿✨",
    likes: 2456,
    comments: 124,
    isLiked: false,
    timestamp: "2026-06-28T18:30:00Z",
  },
  {
    id: 2,
    username: "Lee Min",
    profilePic: "/assets/150 (1).jpg",
    location: "New York, USA",
    image: "/assets/p2.jpg",
    caption: "Weekend vibes 😎",
    likes: 5821,
    comments: 312,
    isLiked: true,
    timestamp: "2026-06-28T15:45:00Z",
  },
  {
    id: 3,
    username: "emma_watson",
    profilePic: "/assets/150 (2).jpg",
    location: "London, UK",
    image: "/assets/p3.jpg",
    caption: "Coffee + Books = Happiness ☕📚",
    likes: 9843,
    comments: 542,
    isLiked: false,
    timestamp: "2026-06-28T10:20:00Z",
  },
  {
    id: 4,
    username: "Sophia",
    profilePic: "/assets/newpic1.jpg",
    location: "Paris, France",
    image: "/assets/newpost1.jpg",
    caption: "Every sunset is a new beginning 🌅✨",
    likes: 4218,
    comments: 198,
    isLiked: false,
    timestamp: "2026-07-01T17:20:00Z",
  },
  {
    id: 5,
    username: "spidzz_pzz",
    profilePic: "/assets/hero.png",
    location: "Bengaluru, India",
    image: "/assets/pics1.jpg",
    video: "/reels/s4.mp4",
    caption: "Supra spotting in Bengaluru! 🔥🏎️",
    likes: 3120,
    comments: 89,
    isLiked: false,
    timestamp: "2026-07-02T12:00:00Z",
  },
  {
    id: 6,
    username: "lunxzz_",
    profilePic: "/assets/pp2.jpg",
    location: "Chennai, India",
    image: "/assets/newpost1.jpg",
    video: "/reels/s7.mp4",
    caption: "Ride day with the crew 🏍️💨",
    likes: 1874,
    comments: 64,
    isLiked: false,
    timestamp: "2026-07-03T09:30:00Z",
  },
  {
    id: 7,
    username: "emma_watson",
    profilePic: "/assets/150 (2).jpg",
    location: "London, UK",
    image: "/assets/pic3.jpg",
    video: "/reels/s1.mp4",
    caption: "Mood 🔥 #viral",
    likes: 5210,
    comments: 143,
    isLiked: false,
    timestamp: "2026-07-04T11:00:00Z",
  },
  {
    id: 8,
    username: "elsa",
    profilePic: "/assets/trumph.jpg",
    location: "Paris, France",
    image: "/assets/p1.jpg",
    video: "/reels/s5.mp4",
    caption: "Venmathi vibes ✨🚗",
    likes: 2980,
    comments: 77,
    isLiked: false,
    timestamp: "2026-07-05T14:20:00Z",
  },
  {
    id: 9,
    username: "elle",
    profilePic: "/assets/elle.jpg",
    location: "New York, USA",
    image: "/assets/p2.jpg",
    video: "/reels/s8.mp4",
    caption: "College diaries 🎓😂",
    likes: 1642,
    comments: 58,
    isLiked: false,
    timestamp: "2026-07-06T16:45:00Z",
  },
];

export const suggestions = [
  { id: 1, username: "Edward", profilePic: "/assets/150.jpg" },
  { id: 2, username: "Lee Min", profilePic: "/assets/150 (1).jpg" },
  { id: 3, username: "emma_watson", profilePic: "/assets/150 (2).jpg" },
  { id: 4, username: "elsa", profilePic: "/assets/trumph.jpg" },
  { id: 5, username: "elle", profilePic: "/assets/elle.jpg" },
  { id: 6, username: "Sophia", profilePic: "/assets/newpic1.jpg" },
];

export const stories = [
  {
    id: 1,
    username: "Edward",
    profilePic: "/assets/150.jpg",
    location: "Chennai, India",
    image: "/assets/pics1.jpg",
  },
  {
    id: 2,
    username: "Lee Min",
    profilePic: "/assets/150 (1).jpg",
    location: "New York, USA",
    image: "/assets/pic2.jpg",
  },
  {
    id: 3,
    username: "emma_watson",
    profilePic: "/assets/150 (2).jpg",
    location: "London, UK",
    image: "/assets/pic3.jpg",
  },
  {
    id: 4,
    username: "elsa",
    profilePic: "/assets/trumph.jpg",
    location: "Paris, France",
    image: "/assets/p1.jpg",
  },
  {
    id: 5,
    username: "elle",
    profilePic: "/assets/elle.jpg",
    location: "New York, USA",
    image: "/assets/p2.jpg",
  },
  {
    id: 6,
    username: "Sophia",
    profilePic: "/assets/newpic1.jpg",
    location: "Paris, France",
    image: "/assets/p3.jpg",
  },
  {
    id: 7,
    username: "lunxzz_",
    profilePic: "/assets/pp2.jpg",
    location: "Chennai, India",
    image: "/assets/newpost1.jpg",
  },
  {
    id: 8,
    username: "spidzz_pzz",
    profilePic: "/assets/hero.png",
    location: "Coimbatore, India",
    image: "/assets/pics1.jpg",
  },
];
